### PR TITLE
Introduce basic INI Parsing and configuration and simplification

### PR DESCRIPTION
**Pull request by spflaumer**
Currently only the HTTPSBlockList, TelemetryBlockList and ExcludeLog Keys work. If no config file is specified default options are used. proxy.Start() configures itself fully.

### CODE REVIEW

**Comment by spflaumer** [comment]
Why are \ preceding all dots in the default blocklist definitions?

**Comment by kyoukaya** [comment]
> Why are \ preceding all dots in the default blocklist definitions?

IIRC it's needed to represent a literal period as its parsed as regex.

I think while your implementation works, ini is a bad fit for most modern config files. I'd used either yaml or json and marshal/unmarshal it to a struct with struct tags.

**Comment by spflaumer** [comment]
makes sense. i'll rewrite the config to use yaml or toml then (depending on what's easier and more suitable)

**Comment by spflaumer** [comment]
i feel like toml might be easier overall as it appears to be more straightforward, so i will rewrite the config as toml

**Pull request closed without merging**
